version: '3.5'

services:
  protocol-record:
    env_file:
      - ./.env
    build: ./
    image: protocol-record
    container_name: protocol-record
    working_dir: /www
    ports:
      - "3003:3003"
    depends_on:
      - test-db

  test-db:
    image: postgres:11
    container_name: test-db
    command: postgres
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=test-db
    tty: true
    ports:
      - 5432:5432
    expose:
      - 5432
