# Default values for helm-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Update these when you copy the chart to your own repo so they match your
# service's specifics.

replicaCount: 1

image:
  repository: kivaprotocol/record
  tag: latest # this will be populated by CD
  pullPolicy: Always

nameOverride: "record"
fullnameOverride: "record"
secrets: "record"

strategy:
  type: "RollingUpdate"

service:
  type: ClusterIP
  port: 6543
  containerPort: 6543
  targetPort: 6543
  portName: http

resources:
  limits:
    cpu: 1100m
    memory: 607164212
  requests:
    cpu: 1100m
    memory: 607164212

readiness:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 1
    path: /healthz

liveness:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 10
    path: /healthz

ingress:
  enabled: false # set to true if component needs ingress
  host: "replaceme.replacethisdomain"
  class: nginx-ingress-external
  secret: "replaceme-tls"

# By default services are stateless
storage:
  enabled: false
  volume: todo-volume-name # we may also need a helm template for the PVC / StorageClass / Volume
  path: /tmp/record-files

# By default services should disable this option as it is used to give the pod
# elevated k8s privileges
serviceAccount:
  enabled: false
  name: agency-kubectl

# Uncomment below to allocate pods to a specific node type.
#
#tolerations:
#  - effect: NoSchedule
#    key: crypto
#    operator: Equal
#    value: "true"
#
#nodeSelector:
#    dedicated: crypto
#
#affinity: {}
